Extension divergence help information in the UI
cdr/code-server pull request #2185
Opened 2020-10-09 19:25 UTC by cmoog

2020-10-09 20:36 UTC, nhooyr requested changes
lgtm otherwise

2020-10-09 20:36 UTC, nhooyr commented on ci/dev/vscode.patch
> -diff --git a/build/lib/extensions.js b/build/lib/extensions.js
Something went wrong with the diff here. I think you need to rebase your branch and clean.

2020-10-09 21:00 UTC, kylecarbs requested changes
```
NOTE: code-server has it's own marketplace of open-source extensions due to 
<a href="https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code" target="_blank">legal distribution restrictions</a>.
VSIX assets from the official marketplace can be 
<a onClick="MAKE THIS EXECUTE THE UPLOAD VSIX COMMAND">uploaded<a/>.
```
Thoughts on something like this?

2020-10-09 21:57 UTC, cmoog commented
@kylecarbs I do think a link to the official marketplace is worth _a lot_.

2020-10-09 22:48 UTC, kylecarbs commented
Oh yeah I'm down to include that.

Just tryna reduce the size of the copy as much as possible.

2020-10-12 17:58 UTC, code-asher commented
Possibly dumb question, is downloading extensions to use in
non-Microsoft products a TOS violation? That's the sense I had but I'm
no lawyer.

2020-10-12 18:13 UTC, code-asher reviewed
Looks good, +1 from me on reducing the copy size as much as possible. Should we store the dismissal state for subsequent page loads or would it be more beneficial have it show more often?

2020-10-12 18:13 UTC, code-asher commented on ci/dev/vscode.patch
> ++NOTE: the code-server extension marketplace is different from the Microsoft VSCode Extension Marketplace. code-server offers it's own
```suggestion
+NOTE: the code-server extension marketplace is different from the Microsoft VSCode Extension Marketplace. code-server offers its own
```

2020-10-14 09:34 UTC, sr229 commented
My nitpick here is use the same caution dialogue indicator used in Git when you're exceeding the 50-character limit so the user will see it immediately, it will add a sense of visual priority of what to read first.

2020-10-14 16:38 UTC, code-asher commented
Hmm, that's an interesting idea, it looks like it pops up below the textbox as you type. I lean toward keeping the current method because that popup floats and would probably cover an extension or two in the search results which could be frustrating. We could only show it if there weren't any results, but I think having results but not the right ones might be a common case (just a guess though) and those cases would never get the help text.

2020-10-14 16:59 UTC, code-asher approved these changes
Looks good to me. BTW if we still want to add a link for jumping directly to the upload we can do it with something like:
```
uploadButton.addEventListener("click", () => {
  this.instantiationService.createInstance(InstallVSIXAction, InstallVSIXAction.ID, InstallVSIXAction.LABEL).run()
});
```

2020-10-14 16:59 UTC, code-asher commented on ci/dev/vscode.patch
> ++		// NODE@coder this UI element helps users understand the extension marketplace divergence
```suggestion
+		// NOTE@coder this UI element helps users understand the extension marketplace divergence
```

2020-10-14 16:59 UTC, code-asher commented on ci/dev/vscode.patch
> ++		const extensinHelperLocalStorageKey = 'coder.extension-help-message';
```suggestion
+		const extensionHelperLocalStorageKey = 'coder.extension-help-message';
```

2020-10-15 18:19 UTC, cmoog commented
Closing this PR as it's become clear that linking to or referencing the existence of the official marketplace is a no-go. Suggesting users to upload via the dropdown has the same problem. Keeping the helper text without including instructions for resolution will cause more confusion than it's worth. Eventually, if we ever move to open-source our extension marketplace, an overlay of this nature will be appropriate. 

😢 I'll open a new PR with a revised issue template for extension requests.

2020-10-15 18:19 UTC, closed without merging