Docs copyedits: README.md + CONTRIBUTING.md
cdr/code-server pull request #2242
Opened 2020-10-27 17:09 UTC by khorne3

The first in a series of edits to the code-server docs.

Changes include copy edits and basic structural reorg to README.md, CONTRIBUTING.md for clarity. All feedback regarding changes welcome.

If it's not a problem, I'd like to move contributing to the root level a la other open-source projects.

2020-10-27 17:50 UTC, nhooyr commented
> If it's not a problem, I'd like to move contributing to the root level a la other open-source projects.

Sounds good!

2020-10-27 19:10 UTC, nhooyr reviewed
Could you justify some of these changes? It's not clear to me what was improved.

2020-10-27 19:11 UTC, nhooyr commented on doc/CONTRIBUTING.md
> +- [Contributing](#contributing)
Use `yarn fmt` to format this, it'll prevent the extra nesting.

2020-10-28 14:25 UTC, khorne3 commented
@nhooyr Sure -- was there anything in particular that stood out for you? My goal is to make docs as clear as possible. The copy edits (spelling, grammar, etc.) are self-explanatory. I had to read some things multiple times to understand, and in some parts, it seemed the context/explanations were reversed.

2020-10-28 16:17 UTC, nhooyr commented
> @nhooyr Sure -- was there anything in particular that stood out for you? My goal is to make docs as clear as possible. The copy edits (spelling, grammar, etc.) are self-explanatory. I had to read some things multiple times to understand (I try to look at things from the perspective of someone who is completely new), and in some parts, it seemed the context/explanations were reversed.

Fair enough! As writer of these docs, I'm very biased in my opinion and understanding of them so I'll defer to you. I'll add some comments.

2020-10-28 16:26 UTC, nhooyr requested changes
Overall 👍🏼

2020-10-28 16:26 UTC, nhooyr commented on README.md
> +2. Manually installing code-server; see [Installation](./doc/install.md#quick-install) for instructions applicable to most use cases
Link here looks wrong.

2020-10-28 16:26 UTC, nhooyr commented on README.md
> +See [CONTRIBUTING](./doc/CONTRIBUTING.md) for additional details.
```suggestion
See [CONTRIBUTING](./doc/CONTRIBUTING.md) for details.
```

2020-10-28 16:26 UTC, nhooyr commented on doc/CONTRIBUTING.md
> +  - [Currently Known Issues](#currently-known-issues)
I like this!

2020-10-28 16:26 UTC, nhooyr commented on doc/CONTRIBUTING.md
> +the VS Code front-end and fills in with the server. You can find this in
```suggestion
the VS Code front-end and implements the server. You can find this in
```

2020-10-28 16:26 UTC, nhooyr commented on doc/CONTRIBUTING.md
> +eliminate our patch. In the meantime, upgrading the VS Code version requires us to ensure that the patch is applied and works as intended. In the future, we'd like to run VS
This line needs to be wrapped shorter.

2020-10-28 16:26 UTC, nhooyr commented on doc/CONTRIBUTING.md
> +- Adding our build file, which includes our code and VS Code's web code
Appreciate the grammar fixes here.

2020-10-29 15:51 UTC, nhooyr approved these changes
Thanks @khorne3

2020-10-29 18:01 UTC, khorne3 commented
@nhooyr What do I need to do re: failing checks?

2020-10-29 19:02 UTC, nhooyr commented on doc/CONTRIBUTING.md
> -<!-- START doctoc generated TOC please keep comment here to allow auto update -->
People may be using this path actively in links and whatnot and us moving it will break.

I think we should just keep it as is.

2020-10-29 19:03 UTC, nhooyr commented
@khorne3 you can ignore those, I'll merge 4 you after my last comment is addressed

2020-10-29 21:21 UTC, nhooyr commented
Thanks again @khorne3

2020-10-29 21:21 UTC, merged