Express refactor: Handlebars templates
cdr/code-server pull request #2246
Opened 2020-10-28 21:18 UTC by TeffenEllis

- Fixed issue where JSON entities may be unescaped
- Updated web manifest schema, route handler.

2020-11-03 19:53 UTC, code-asher requested changes
Handlebars + static combo-wombo! This looks great! ty again for taking care of this.

2020-11-03 19:53 UTC, code-asher commented on src/node/routes/index.ts
> +        ERROR_BODY: err.message,
I really like how clean these template vars became.

2020-11-03 19:53 UTC, code-asher commented on src/node/routes/manifest.ts
> +const iconSizes = [96, 128, 192, 256, 384, 512]
Dope that we don't have to manually add each one now.

2020-11-03 19:53 UTC, code-asher commented on src/browser/views/error.handlebars
> +    <link href="{{assetPath csStaticBase '/register.css'}}" rel="stylesheet" />
```suggestion
    <link href="{{assetPath base '/register.css'}}" rel="stylesheet" />
```

Or `<link href="{{assetPath base '/dist/register.css'}}" rel="stylesheet" />` if we end up moving the `dist` endpoint.

2020-11-03 19:53 UTC, code-asher commented on src/node/app.ts
> +         * @TODO we can likely move JSON attributes to <script type="text/json">
:+1: love this idea

2020-11-03 19:56 UTC, TeffenEllis commented on src/node/routes/login.ts
> +    rootHandler(error, req, res, next)
I believe it does just as a virtue of using the `ErrorRequestHandler` 🙃

2020-11-04 17:28 UTC, code-asher commented on src/node/routes/login.ts
> +    rootHandler(error, req, res, next)
Ahh oops makes sense.

2020-11-04 21:05 UTC, code-asher reviewed
Latest changes look great! There are still some unresolved comments (looks like they're being collapsed and hidden though).

2020-11-21 18:08 UTC, Qreig approved these changes

2020-11-30 22:47 UTC, code-asher commented
I haven't been able to re-review this yet. The divergence is growing and I'm not totally sure the best way to proceed but here's my plan:

1. Close to keep the PR queue slim.
2. Rebase on master.
3. Split up the commit a bit.
4. Open a new PR.

Additionally, we had a discussion about Handlebars and we want to try taking a route that lets us have type checking in the template (if we do though it'll basically just be replacing the `.hbs` files, so not a huge departure).

2020-11-30 22:47 UTC, closed without merging

2021-01-08 00:57 UTC, nhooyr commented
Deleted this branch for now. I have it locally and saved on my fork in case we need to access these commits again. Just trying to keep the main repositories branches clean.

2021-01-08 01:23 UTC, nhooyr commented
For posterity, the link is https://github.com/nhooyr/code-server/tree/z/handlebars-templates