add instructions for deploying to a cloud provider
cdr/code-server pull request #2843
Opened 2021-03-08 21:34 UTC by bpmct

I have been working on the [cdr/deploy-code-server](https://github.com/cdr/deploy-code-server which includes one-click buttons and guides to deploy code-server to a cloud provider, such as Linode or Heroku.

![deploy-code-server repo](https://user-images.githubusercontent.com/22407953/110383876-f017b780-802a-11eb-81e5-dafd92f76b58.png)

@jsjoeio and I have been discussing including parts of this in the code-server repo, as it is a great way to get started using it. It is only a few steps to get an environment that can be accessed from anywhere!

However, I think that we cannot simply add all of the docs and guides to this repo. Here's why:

- Certain providers (such as Heroku and Railway) require that some info lives in the base directory of the repository, such as the [heroku.yml](https://github.com/cdr/deploy-code-server/blob/main/heroku.yml) flle. This would mess up code-server's folder structure.
- Since the latest code-server version is the default branch, users will not see updates for deploy options until the next version. We may add support for other cloud providers or add fixes before then
- Providers like Railway and Heroku involve the user "forking" the repo to their account so they can modify their environment. It wouldn't be ideal for the user to fork the whole code-server codebase 

However, it may be valuable to add links to deploy to certain providers instead of linking to the entire project. We could include a partial table to README or install.md to include this info?

Currently, our [install.md](https://github.com/cdr/code-server/blob/main/docs/install.md#app-engines-azure-heroku) currently has (now outdated) instructions for deploying. We could also add there.

2021-03-08 21:56 UTC, jsjoeio requested changes
I like what you added to the `README.md`. 

> I think the source-of-truth for the docs and guides should live on the separate deploy-code-server repo though

Agreed! I like the approach you've taken - add a short text snippet and link out to that repo.

I think we should update the `install.md` as well like you said then merge this

2021-03-08 21:56 UTC, jsjoeio commented on README.md
> +3. Use our one-click buttons and guides to [deploy code-server to a popular cloud provider](https://github.com/cdr/deploy-code-server)
I think this is perfect!

2021-03-08 22:12 UTC, bpmct commented
So, currently the install script takes up a large % of the README, which I think is good. However, are there potentially other things we could do to draw attention to this "quick deploy" option?

A few ideas:
- put a badge like this somewhere (lol): [![deploy-code-server](https://img.shields.io/badge/deploy%20to-cloud%20providers-grey?style=flat-square&logo=icloud&labelColor=blue&logoColor=white)](https://github.com/bpmct/deploy-code-server) 
- add a small table/button to deploy to ONE cloud provider, which links to the guide on the external repo
- do nothing, step 3 will be visible enough for more people :)

2021-03-08 22:14 UTC, jsjoeio commented
I could be on board with any of those options! I'll defer to you on which you think is best :D

2021-03-09 00:01 UTC, bpmct commented
Ok just added an emoji lol

2021-03-09 22:04 UTC, merged