feat(lib/vscode): add log out to application menu
cdr/code-server pull request #2922
Opened 2021-03-17 22:37 UTC by jsjoeio

This adds a new option to the Application Menu called Log out. It deletes the code-server cookie and logs a user out.

## Screenshot
![2021-03-17 15 31 46](https://user-images.githubusercontent.com/3806031/111547536-8c7e4000-8736-11eb-8b1a-a6294b51757d.gif)

## TODOs
- [ ] figure out why coder/logger isn't working (GET 404 in browser when imported into file)

Fixes #778

2021-03-18 05:04 UTC, oxy requested changes
LGTM! Just a newline at the end of `lib/vscode/src/vs/server/common/cookie.ts` should be all that's needed.

2021-03-18 05:04 UTC, oxy commented on lib/vscode/src/vs/server/common/cookie.ts
> +}
Missing a newline at the end of the file.

2021-03-18 08:53 UTC, oxy commented
So I was wondering why `tsc` was "failing" to use `outDir`...

Turns out it was, but since we import from `lib/vscode` in `src` now, what used to be `out/node/entry.js` has now become `out/src/node/entry.js` (and there's an `out/lib/vscode/.../cookie.js`).

Since our build script, `./ci/steps/build-code-server.sh` looks for `out/node/entry.js`, it fails.

2021-03-18 08:55 UTC, oxy commented on test/unit/util.test.ts
> +import { Cookie as CookieEnum } from "../../lib/vscode/src/vs/server/common/cookie"
Importing this from `lib/vscode` breaks the expected directory structure in `out`, see https://github.com/cdr/code-server/pull/2922#issuecomment-801746756

2021-03-18 15:16 UTC, jsjoeio commented
> I think it might be best to just duplicate the key cookie.

Ah okay. Yeah it doesn't seem worth it to have to fix everything else for one thing to not be duplicated 😂 thanks for looking into this! I'll convert to draft and fix!

2021-03-22 19:19 UTC, oxy approved these changes
LGTM!

2021-03-22 22:15 UTC, bpmct commented
Love this!

2021-03-23 19:44 UTC, merged

2021-03-24 10:18 UTC, binaryfire commented
Nice! Just a thought - can you also add it to the profile icon at the bottom of the left sidebar? That seems like the most intuitive place to look for it.

2021-03-24 17:36 UTC, jsjoeio commented
@binaryfire thanks for the suggestion! There's some issues with the profile icon (see #2913) but when we work on that, we can consider it! Feel free to leave more thoughts there